#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to respect following requirements
# Requirements:
#   Install nginx on your web-01 server
#   Nginx should be listening on port 80
#   When querying Nginx at its root / with a GET request (requesting a page) using curl,
#   it must return a page that contains the string Hello World!

# Install the Nginx web server software.
apt-get update -y
apt-get install -y nginx

# Create a directory to store the website files.
mkdir /var/www/html

# Write "Hello World!" to the index.html file.
echo "Hello World!" > /var/www/html/index.html

# Create a custom Nginx configuration file for the website.
# This configuration file sets up Nginx to listen on port 80 and serve files from /var/www/example.com/html.
# It also specifies index.html, index.htm, and index.nginx-debian.html as the default index files.
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    listen [::]:80;
    root /var/www/example.com/html;
    index index.html index.htm index.nginx-debian.html;
}
EOF

# Restart the Nginx service to apply the new configuration.
service nginx restart
