#!/usr/bin/env bash
# This script installs and configures the Nginx web server software.

HOSTNAME=$(hostname)

# Install the Nginx web server software.
apt-get update -y
apt-get install -y nginx

# Write "Hello World!" to the index.html file.
echo "Hello World!" > /var/www/html/index.html

# Create the custom 404 page.
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx server
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    add_header X-Served-By "$HOSTNAME";

    error_page 404 /404.html;
    location /404.html {
        root /var/www/html;
        internal;
    }
}
EOF

# Restart the Nginx service to apply the new configuration.
service nginx restart
