#!/usr/bin/env bash
# This script installs and configures HAProxy.
# It updates package lists, installs HAProxy, enables HAProxy in /etc/default/haproxy,
# backs up the original HAProxy configuration file, creates a new configuration file,
# and then restarts the HAProxy service.

# Update package lists and Install HAProxy
apt-get update -y
apt-get install -y haproxy

# Enable HAProxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Back up the original HAProxy configuration file
mv /etc/haproxy/haproxy.cfg{,.original}

# Create a new HAProxy configuration file
cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log     127.0.0.1 local0 notice
    maxconn 2000
    user    haproxy
    group   haproxy

defaults
	log     global
	mode    http
	option  httplog
	option  dontlognull
	retries 3
	option  redispatch
	timeout connect  5000
	timeout client  10000
	timeout server  10000

listen alx
    bind    *:80
    mode    http
    stats   enable
    stats   uri /haproxy?stats
    balance roundrobin
    option  httpclose
    option  forwardfor
    server  508797-web-01 3.83.253.65:80 check
    server  508797-web-02 3.84.239.237:80 check
EOF

# Restart the HAProxy service
service haproxy restart
